name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Đăng nhập vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build và push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/react-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/react-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Chỉ deploy khi push vào main

    steps:
      # 1. Deploy lên server qua SSH với mật khẩu
      - name: Deploy to Server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          # Cài sshpass
          sudo apt-get update && sudo apt-get install -y sshpass
          # Deploy qua SSH với các thông tin từ secrets
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-app:latest
            docker stop react-app || true
            docker rm react-app || true
            docker run -d --name react-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/react-app:latest
          EOF